# Changes here will be overwritten by Copier
SelectCitation:
- AddCitationFile_flag
- AddCFFConvert_flag
SelectCodeQualityFeatures:
- AddLocalTests_flag
- SelectGitHubActions_flag
- AddLinting_flag
- AddSonarCloud_flag
SelectCommunityFeatures:
- AddCodeConduct_flag
- AddContributing_flag
SelectDocumentationFeatures:
- AddDevDoc_flag
SelectGitHubActions:
- AddGitHubActionBuild_flag
SelectPublishReleaseFeatures:
- SelectCitation_flag
- AddChangeLog_flag
- AddZenodo_flag
_commit: 0.6.1
_src_path: https://github.com/nlesc/python-template.git
code_of_conduct_email: d.smits@esciencecenter.nl
copyright_holder: Djura Smits
email: d.smits@esciencecenter.nl
full_name: Djura Smits
github_organization: OSLA-project
keywords: ''
license: Apachev2
package_name: openlab_vu
package_short_description: Configuration of openlab for VU lab
template_profile: recommended
version: 0.1.0
