# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations

from typing import TYPE_CHECKING

from sila2.server import MetadataDict

import asyncio as aio
from pylabrobot.plate_reading import BioTekPlateReaderBackend

from ..generated.synergyhtx import OpenTray_Responses, SynergyHTXBase


if TYPE_CHECKING:
    from ..server import Server


class SynergyHTXImpl(SynergyHTXBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self.plate_reader = BioTekPlateReaderBackend()

    def get_SerialNumber(self, *, metadata: MetadataDict) -> str:
        aio.run(self.plate_reader.get_serial_number())

    def OpenTray(self, *, metadata: MetadataDict) -> OpenTray_Responses:
        self.plate_reader.open_tray()
