# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations

from typing import TYPE_CHECKING

from sila2.server import MetadataDict

from ..generated.synergyhtx import CloseTray_Response, OpenTray_Response, SynergyHTXBase

if TYPE_CHECKING:
    from ..server import Server

import asyncio as aio
import openlab_vu.platereader.controller.types as T
from openlab_vu.platereader.controller.synergy import SynergyHTXBackend


class SynergyHTXImpl(SynergyHTXBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self.plate_reader = SynergyHTXBackend()
        self.tray_state = T.TrayState.Unknown

    def get_SerialNumber(self, *, metadata: MetadataDict) -> str:
        try:
            print(f"==[ Getting serial number")
            sn = aio.run(self.plate_reader.get_serial_number())
        except Exception as e:
            sn = ""
        finally:
            return sn

    def OpenTray(self, *, metadata: MetadataDict) -> OpenTray_Response:
        try:
            print(f"==[ Opening tray")
            aio.run(self.plate_reader.open_tray())
            self.tray_state = T.TrayState.Open
        except Exception as e:
            self.tray_state = T.TrayState.Unknown
        finally:
            return OpenTray_Response(self.tray_state.value)

    def CloseTray(self, *, metadata: MetadataDict) -> CloseTray_Response:
        try:
            print(f"==[ Closing tray")
            aio.run(self.plate_reader.close_tray())
            self.tray_state = T.TrayState.Closed
        except Exception as e:
            self.tray_state = T.TrayState.Unknown
        finally:
            return CloseTray_Response(self.tray_state.value)
