# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations

from typing import TYPE_CHECKING

from sila2.server import MetadataDict

from ..generated.synergyhtx import (
    SynergyHTXBase,
    OpenTray_Responses,
    CloseTray_Responses,
    SetPlate_Responses,
    RemovePlate_Responses,
    ReadTemperature_Responses,
    ReadAbsorbance_Responses,
    ReadFluorescence_Responses,
    ReadLuminescence_Responses,
    GetSerialNumber_Responses,
    GetPlateName_Responses,
)
from datetime import datetime
from zoneinfo import ZoneInfo
from pathlib import Path
from loguru import logger
import asyncio as aio

from pylabrobot.resources import Plate, Well, thermo_AB_96_wellplate_300ul_Vb_MicroAmp
from openlab_vu.platereader.controller.synergy import SynergyHTXController

if TYPE_CHECKING:
    from ..server import Server


class SynergyHTXImpl(SynergyHTXBase):
    """SiLA feature implementation for the BioTek Synergy HTC plate reader.

    This class relies on the BioTek plate reader interface
    from PyLabRobot (https://github.com/PyLabRobot/PyLabRobot).
    """

    def __init__(
        self,
        parent_server: Server | None = None,
    ) -> None:
        super().__init__(parent_server=parent_server)
        self.controller = SynergyHTXController()
        aio.run(self.controller.setup())

    def GetSerialNumber(self, *, metadata: MetadataDict) -> GetSerialNumber_Responses:
        """
        Get the serial number of the device.

        Args:
            metadata: Metadata provided by the client.

        Returns:
            A GetSerialNumber_Responses instance.
        """

        return aio.run(self.controller.get_serial_number())

    def OpenTray(self, *, metadata: MetadataDict) -> OpenTray_Responses:
        """
        Open the device tray.

        Args:
            metadata: Metadata provided by the client.

        Returns:
            An OpenTray_Responses instance.
        """

        ts = aio.run(self.controller.open_tray())
        return ts.value

    def CloseTray(self, *, metadata: MetadataDict) -> CloseTray_Responses:
        """
        Close the device tray.

        Args:
            metadata: Metadata provided by the client.

        Returns:
            A CloseTray_Responses instance.
        """

        ts = aio.run(self.controller.close_tray())
        return ts.value

    def SetPlate(
        self,
        plate_id: int,
        *,
        metadata: MetadataDict,
    ) -> SetPlate_Responses:
        """
        Version of set_plate() for use with SiLA.

        Args:
            plate_id: Plate ID.
            metadata: Metadata provided by the client.

        Returns:
            A SetPlate_Responses instance.
        """

        # TODO: Get a plate from the database
        # and set up a Plate instance.
        # plate = ...
        # For now, all wells are used.

        plate = thermo_AB_96_wellplate_300ul_Vb_MicroAmp("test_plate")
        wells = [plate.get_item(i) for i in range(plate.num_items)]
        return aio.run(self.controller.set_plate(plate, wells))

    def RemovePlate(
        self,
        *,
        metadata: MetadataDict,
    ) -> RemovePlate_Responses:
        """
        Version of remove_plate() for use with SiLA.

        Args:
            metadata: Metadata provided by the client.

        Returns:
            A RemovePlate_Responses instance.
        """

        return aio.run(self.controller.remove_plate())

    def GetPlateName(self, *, metadata: MetadataDict) -> GetPlateName_Responses:
        """
        Get the name of the currently loaded plate.

        Args:
            metadata: Metadata provided by the client.

        Returns:
            A GetPlateName_Responses instance.
        """
        return aio.run(self.controller.get_plate_name())

    def ReadTemperature(self, *, metadata: MetadataDict) -> ReadTemperature_Responses:
        """
        Read the device temperature.

        Args:
            metadata: Metadata provided by the client.

        Returns:
            A ReadTemperature_Responses instance.
        """

        return aio.run(self.controller.read_temperature())

    def ReadAbsorbance(
        self,
        wavelength: int,
        *,
        metadata: MetadataDict,
    ) -> ReadAbsorbance_Responses:
        """
        Read the absorbance of the wells in the currently loaded plate.

        Args:
            wavelength: Wavelength used for reading the absorbance.
            metadata: Metadata provided by the client.

        Returns:
            A ReadAbsorbance_Responses instance.
        """

        result = aio.run(self.controller.read_absorbance(wavelength))
        if result is None:

            return (
                wavelength,
                0.0,
                datetime.now(tz=ZoneInfo(self.tz)),
            )
        return (result.get(item) for item in ("wavelength", "temperature", "time"))

    def ReadFluorescence(
        self,
        excitation_wavelength: int,
        emission_wavelength: int,
        focal_height: float,
        *,
        metadata: MetadataDict,
    ) -> ReadFluorescence_Responses:
        """
        Read the fluorescence of the wells in the currently loaded plate.

        Args:
            excitation_wavelength: The excitation wavelength.
            emission_wavelength: The emission wavelength.
            focal_height: The focal height of the plate.
            metadata: Metadata provided by the client.

        Returns:
            A ReadFluorescence_Responses instance.
        """

        result = aio.run(
            self.controller.read_fluorescence(
                excitation_wavelength, emission_wavelength, focal_height
            )
        )
        if result is None:
            return (
                excitation_wavelength,
                emission_wavelength,
                focal_height,
                0.0,
                datetime.now(tz=ZoneInfo(self.tz)),
            )

        return (
            result.get(item)
            for item in (
                "ex_wavelength",
                "em_wavelength",
                "temperature",
                "time",
            )
        )

    def ReadLuminescence(
        self,
        focal_height: float,
        integration_time: float,
        *,
        metadata: MetadataDict,
    ) -> ReadLuminescence_Responses:
        """
        Read the luminescence of the wells in the currently loaded plate.

        Args:
            focal_height: The focal height of the plate.
            integration_time: Integration time.
            metadata: Metadata provided by the client.

        Returns:
            A ReadLuminescence_Responses instance.
        """

        result = aio.run(
            self.controller.read_luminescence(
                focal_height,
                integration_time,
            )
        )
        if result is None:
            # TODO Store the data by using the user-supplied
            # destination directory (self.save_dir).
            # data = result.get('data', None)
            return (
                0.0,
                datetime.now(tz=ZoneInfo(self.tz)),
            )

        return (
            result.get(item)
            for item in (
                "temperature",
                "time",
            )
        )
