# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations

from typing import TYPE_CHECKING, List

from sila2.server import MetadataDict

from ..generated.synergyhtx import (
    CloseTray_Responses,
    OpenTray_Responses,
    ReadAbsorbance_Responses,
    ReadTemperature_Responses,
    SynergyHTXBase,
)

if TYPE_CHECKING:
    from ..server import Server


class SynergyHTXImpl(SynergyHTXBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

    def get_SerialNumber(self, *, metadata: MetadataDict) -> str:
        raise NotImplementedError  # TODO

    def OpenTray(self, *, metadata: MetadataDict) -> OpenTray_Responses:
        raise NotImplementedError  # TODO

    def CloseTray(self, *, metadata: MetadataDict) -> CloseTray_Responses:
        raise NotImplementedError  # TODO

    def ReadTemperature(self, *, metadata: MetadataDict) -> ReadTemperature_Responses:
        raise NotImplementedError  # TODO

    def ReadAbsorbance(
        self, Plate: int, Wells: List[int], Wavelength: int, *, metadata: MetadataDict
    ) -> ReadAbsorbance_Responses:
        raise NotImplementedError  # TODO
