# Generated by sila2.code_generator; sila2.__version__: 0.14.0

from typing import Optional
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.synergyhtx_impl import SynergyHTXImpl
from .generated.synergyhtx import SynergyHTXFeature


class Server(SilaServer):

    def __init__(
        self,
        server_uuid: Optional[UUID] = UUID("d1aac3fa-3977-45d7-ac09-553ef99d6625"),
        name: Optional[str] = None,
        description: Optional[str] = None,
    ):
        if name is None:
            name = "Synergy HTX"
        if description is None:
            description = "Biotek Synergy HTX plate reader"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type="TODO",
            server_version="0.1",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.synergyhtx = SynergyHTXImpl(self)
        self.set_feature_implementation(SynergyHTXFeature, self.synergyhtx)
